# Generated by Django 5.1.1 on 2024-11-27 06:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_cyber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='vid/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
