# Generated by Django 5.1.1 on 2024-11-12 19:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
