# Generated by Django 5.1.1 on 2024-11-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('dinak', models.DateField()),
                ('thumbnail_image', models.FileField(default=None, max_length=250, null=True, upload_to='thumbnail/')),
            ],
        ),
    ]
