# Generated by Django 5.1.1 on 2024-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumb',
            name='thumbnail_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='thumbnail/'),
        ),
    ]
